### ISSUE TITLE
test with Classic ActiveMQ

### ISSUE THREAD

**Issue by amircogan** [vrslev/stompman#87]
Hi,

This seems like the best asyncio implementation of STOMP. Thanks!!.
The readme says it was tested with Artemis ActiveMQ. I was wondering if there is any experience with Classic ActiveMQ testing as we probably need to use that one.

Thanks!!

**Comment by vrslev** [comment]
Hi! Thanks for your kind words ☺️

Does Classic ActiveMQ has a Docker image I can use in integration tests?

**Comment by amircogan** [comment]
Hi,

Yes, please see at:
https://hub.docker.com/r/apache/activemq-classic/tags

Thanks!!

**Comment by vrslev** [comment]
Ok, I'll look into it later, thanks!

**Comment by vrslev** [comment]
Hi! Now `stompman` is tested both on ActiveMQ Artemis and ActiveMQ Classic. There were one thing that needed to be fixed: #92—it is already in 1.6.0.

**Comment by amircogan** [comment]
Great, many thanks, will try it soon
